### ISSUE TITLE
Publish the package ?

### ISSUE THREAD

**Issue by jpic** [sinisaos/wtf-tortoise#1]
Hi,

Great source code! Thank you for sharing :pray:

Do you plan to release it on PyPi ?

**Comment by sinisaos** [comment]
@jpic thanks for the kind words. I don't have plan to release it on PyPi but you can use it, fork it or do what you want with this repo. It's basically code from wtforms.ext with some modifications to work with Tortoise ORM. For async ORM take a look at [Piccolo ORM](https://github.com/piccolo-orm) wich is awesome (migrations, SQL-like syntax, easy to use). With Piccolo ORM you get whole ecosystem with web admin ([piccolo_admin](https://github.com/piccolo-orm/piccolo_admin)) and [piccolo_api](https://github.com/piccolo-orm/piccolo_api) (ASGI middleware for authentication, rate limiting, and building CRUD endpoints) for easy build web apis. Cheers.

**Comment by jpic** [comment]
Thank you for your reply @sinisaos, I did check your other repos and that's how I found about piccolo.

I've seen piccolo ORM but at the end I went for async SQLAlchemy (1.4b) I'm trying to recreate a django-like experience with starlette, except that instead of templates we use isomorphic python components with websocket based data binding, and except of having auto-generated MVC only for the admin and with not-really-good security features we have OOTB secure (per object, per field, per user) autogenerated Google Material Components frontend.

I'm seeing they also make https://targ.readthedocs.io/en/latest/index.html which is really similar to cli2
